services:
  iptv:
    image: v1st233/iptv:latest
    container_name: iptv-web
    # 进阶功能所需高权限
    privileged: true
    ports:
      - "8090:80" # 不支持host模式，存在不少的端口冲突
    volumes:
      - ./data:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/version"]
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 3
